INSERT INTO SHIPPING_PROVIDER (id, PROVIDER, PACKAGE_SIZE, PRICE) VALUES (1, 'LP', 'S', 1.50);
INSERT INTO SHIPPING_PROVIDER (id, PROVIDER, PACKAGE_SIZE, PRICE) VALUES (2, 'LP', 'M', 4.90);
INSERT INTO SHIPPING_PROVIDER (id, PROVIDER, PACKAGE_SIZE, PRICE) VALUES (3, 'LP', 'L', 6.90);
INSERT INTO SHIPPING_PROVIDER (id, PROVIDER, PACKAGE_SIZE, PRICE) VALUES (4, 'MR', 'S', 2.00);
INSERT INTO SHIPPING_PROVIDER (id, PROVIDER, PACKAGE_SIZE, PRICE) VALUES (5, 'MR', 'M', 3.00);
INSERT INTO SHIPPING_PROVIDER (id, PROVIDER, PACKAGE_SIZE, PRICE) VALUES (6, 'MR', 'L', 4.00);